//! The one path a request takes when it is refused before a verb runs.
//!
//! Every refusal does exactly the same three things: it logs, it writes
//! **zero** response bytes, and it closes the stream cleanly. That holds
//! whether the stream is a bare `AF_UNIX` socket or the TLS stream on
//! top of one: `close()` is `shutdown()`, which on a
//! `tokio_rustls::server::TlsStream` emits `close_notify`, so a refused
//! caller reads an orderly end of stream and not a truncation. There is no
//! wire error, no empty frame and no status code, so a caller learns
//! that it was refused and nothing whatever about which of the daemon's
//! checks it tripped. The operator learns all of it, from the log.
//!
//! What ties the two halves together is the connection diagnostic id.
//! It is generated by the daemon after accept, is never caller-supplied,
//! never appears on the wire and never appears in an audit record — it
//! correlates the lines of one connection in one process's log and does
//! nothing else. It is deliberately shaped unlike the verb layer's
//! request id, which is a correlation handle for a verb invocation that
//! did happen.

use std::fmt;
use std::sync::atomic::{AtomicU64, Ordering};

use tokio::io::{AsyncWrite, AsyncWriteExt as _};
use tracing::warn;

use super::frame::{MalformedNameCause, Operation, escape_name_bytes};
use super::handler::HANDLER_REJECTED_PAYLOAD;

/// Monotonic source of connection diagnostic ids.
static CONNECTION_SEQUENCE: AtomicU64 = AtomicU64::new(0);

/// A daemon-generated correlation handle for one accepted connection.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct ConnectionId(String);

impl ConnectionId {
    /// Assigns the next id. Called once per accepted connection, before
    /// any byte of it is read.
    pub(crate) fn next() -> Self {
        let sequence = CONNECTION_SEQUENCE.fetch_add(1, Ordering::Relaxed);
        Self(format!("endpoint-conn-{sequence}"))
    }

    /// Returns the handle.
    pub(crate) fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for ConnectionId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

/// Which stage of the frame a partial read stopped in.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum PartialStage {
    /// Between the first byte and the complete five-byte prefix.
    Prefix,
    /// Between the prefix and the complete operation name.
    OperationName,
    /// Between the complete header and the complete payload.
    Payload,
}

impl fmt::Display for PartialStage {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Prefix => "prefix",
            Self::OperationName => "operation-name",
            Self::Payload => "payload",
        })
    }
}

/// How a partial or absent frame ended.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum FrameEnd {
    /// The peer closed, or the connection failed, before the stage
    /// completed.
    Eof,
    /// The applicable cumulative deadline expired.
    Deadline,
}

impl fmt::Display for FrameEnd {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Eof => "eof",
            Self::Deadline => "deadline",
        })
    }
}

/// The closed set of pre-verb transport refusals, in the order a
/// connection can reach them.
///
/// Closed at seven on purpose. Each one is something the transport
/// itself observed, and anything a *layer above* observes — a payload a
/// codec cannot decode, say — is not a transport reason and does not
/// join this enum; see [`super::handler::HandlerRefusal`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum TransportRefusalReason {
    /// The endpoint is already serving [`super::MAX_CONCURRENT_CONNECTIONS`].
    /// Capacity is taken after accept and before the spawn, so this
    /// connection is answered and closed on the accept loop's own task
    /// rather than left in the backlog or given a task of its own.
    OverCapacity,
    /// The peer's uid is not this daemon's effective uid.
    UnauthorizedPeer {
        /// The peer's uid, as the kernel reported it.
        peer_uid: u32,
        /// The uid a peer must have.
        expected_uid: u32,
    },
    /// A clean EOF before any request byte, or the header deadline
    /// expiring before any request byte.
    NoHeader {
        /// Which of the two it was.
        end: FrameEnd,
    },
    /// The declared payload length exceeds
    /// [`super::MAX_FRAME_PAYLOAD_BYTES`]. Refused before the name or
    /// body bytes are read and before anything is allocated for them.
    OverLongFrame {
        /// The declared payload length.
        declared: u32,
        /// The largest length that would have been accepted.
        limit: usize,
    },
    /// At least one request byte arrived, but the frame did not
    /// complete.
    PartialFrame {
        /// Where it stopped.
        stage: PartialStage,
        /// How it stopped.
        end: FrameEnd,
        /// How many bytes of that stage had arrived.
        received: usize,
        /// How many that stage needed.
        expected: usize,
    },
    /// The operation-name field is not a name at all.
    MalformedHeader {
        /// Which rule it broke.
        cause: MalformedNameCause,
    },
    /// A syntactically valid, complete name that is neither `mint` nor
    /// `deregister`.
    UnrecognizedOperation,
}

impl TransportRefusalReason {
    /// A stable, lowercase label for the log's `reason` field.
    pub(crate) fn label(&self) -> &'static str {
        match self {
            Self::OverCapacity => "over-capacity",
            Self::UnauthorizedPeer { .. } => "unauthorized-peer",
            Self::NoHeader { .. } => "no-header",
            Self::OverLongFrame { .. } => "over-long-frame",
            Self::PartialFrame { .. } => "partial-frame",
            Self::MalformedHeader { .. } => "malformed-header",
            Self::UnrecognizedOperation => "unrecognized-operation",
        }
    }
}

impl fmt::Display for TransportRefusalReason {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::OverCapacity => write!(
                f,
                "the endpoint is already serving {} connections",
                super::MAX_CONCURRENT_CONNECTIONS
            ),
            Self::UnauthorizedPeer {
                peer_uid,
                expected_uid,
            } => write!(
                f,
                "the peer's uid {peer_uid} is not this daemon's effective uid {expected_uid}"
            ),
            Self::NoHeader { end } => write!(f, "no request byte arrived ({end})"),
            Self::OverLongFrame { declared, limit } => write!(
                f,
                "the declared payload length {declared} exceeds the {limit}-byte limit"
            ),
            Self::PartialFrame {
                stage,
                end,
                received,
                expected,
            } => write!(
                f,
                "the {stage} stage stopped at {received} of {expected} bytes ({end})"
            ),
            Self::MalformedHeader { cause } => write!(f, "{cause}"),
            Self::UnrecognizedOperation => f.write_str("the operation name is not a known verb"),
        }
    }
}

/// Everything a refusal is logged with.
///
/// The operation is an [`Option`] because most refusals happen before
/// one is known, and an absent one is logged as an explicit unread
/// marker rather than as an empty string or an invented name.
#[derive(Debug)]
pub(crate) struct Refusal<'a> {
    /// Why the connection is being refused.
    pub(crate) cause: RefusalCause,
    /// The recognized operation, when one was recognized.
    pub(crate) operation: Option<Operation>,
    /// The operation-name bytes as they arrived, when any were read.
    /// Logged separately from `operation` and always escaped.
    pub(crate) received_name: Option<&'a [u8]>,
}

impl<'a> Refusal<'a> {
    /// A transport refusal with no operation known.
    pub(crate) fn transport(reason: TransportRefusalReason) -> Self {
        Self {
            cause: RefusalCause::Transport(reason),
            operation: None,
            received_name: None,
        }
    }

    /// A refusal of the identity that completed the handshake. No
    /// request byte has been read at this point, so there is no
    /// operation and no received name to attach.
    pub(crate) fn caller_identity(refusal: CallerIdentityRefusal) -> Self {
        Self {
            cause: RefusalCause::CallerIdentity(refusal),
            operation: None,
            received_name: None,
        }
    }

    /// Attaches the operation-name bytes that were read.
    #[must_use]
    pub(crate) fn with_received_name(mut self, bytes: &'a [u8]) -> Self {
        self.received_name = Some(bytes);
        self
    }

    /// Attaches the recognized operation.
    #[must_use]
    pub(crate) fn with_operation(mut self, operation: Operation) -> Self {
        self.operation = Some(operation);
        self
    }

    /// A handler's refusal of the payload, routed through this same
    /// path.
    pub(crate) fn handler_rejected_payload(operation: Operation) -> Self {
        Self {
            cause: RefusalCause::HandlerRejectedPayload,
            operation: Some(operation),
            received_name: None,
        }
    }
}

/// Why the caller that completed a handshake is not one this endpoint
/// serves.
///
/// Decided *after* the handshake rather than inside a
/// `ClientCertVerifier`, for two reasons that both matter. A verifier
/// lives in the `ServerConfig` and is shared by every connection, so it
/// cannot log under the connection diagnostic id that correlates the
/// rest of that connection's lines; and a rejection from inside it is a
/// TLS alert, which would be a second refusal shape beside the silent
/// clean close every other pre-verb refusal uses. Nothing is read from
/// the caller before this check, so "refused before any request is
/// read" still holds.
///
/// Chain verification is not in here at all — that is
/// `WebPkiClientVerifier`'s, and a chain that does not build never
/// reaches this point.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum CallerIdentityRefusal {
    /// The handshake completed but the session carries no peer
    /// certificate to recognize. The verifier makes a client
    /// certificate mandatory, so this is a contradiction rather than an
    /// expected arm — and it is refused rather than assumed away.
    NoPeerCertificate,
    /// The peer's certificate verified against the deployment CA but is
    /// not the registrar client identity.
    NotRegistrarClient {
        /// Which rule of the name the presented leaf broke.
        source: crate::registrar::RegistrarIdentityError,
    },
}

impl CallerIdentityRefusal {
    /// A stable, lowercase label for the log's `reason` field.
    fn label(self) -> &'static str {
        match self {
            Self::NoPeerCertificate => "no-peer-certificate",
            Self::NotRegistrarClient { .. } => "not-registrar-client",
        }
    }
}

impl fmt::Display for CallerIdentityRefusal {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NoPeerCertificate => f.write_str(
                "the completed handshake carries no peer certificate to recognize an identity from",
            ),
            Self::NotRegistrarClient { source } => write!(
                f,
                "the peer's certificate is not the registrar client identity: {source}"
            ),
        }
    }
}

/// What is being refused: one of the seven transport reasons, a
/// handshake that verified as the wrong identity, or a handler's
/// rejection of the payload.
///
/// Three variants rather than nine: neither the identity refusal nor
/// the handler's rejection joins the transport taxonomy — each of those
/// seven reasons is something *the transport* observed about the frame
/// — but both share this path, with the same zero response bytes, the
/// same clean close and the same connection id.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum RefusalCause {
    /// One of the seven transport reasons.
    Transport(TransportRefusalReason),
    /// The handshake completed, but not as the one identity this
    /// endpoint serves.
    CallerIdentity(CallerIdentityRefusal),
    /// The handler rejected the payload bytes before a verb ran.
    HandlerRejectedPayload,
}

impl RefusalCause {
    /// The `reason` field's stable label.
    fn label(&self) -> &'static str {
        match self {
            Self::Transport(reason) => reason.label(),
            Self::CallerIdentity(refusal) => refusal.label(),
            Self::HandlerRejectedPayload => "handler-rejected-payload",
        }
    }

    /// The human-readable cause.
    fn describe(&self) -> String {
        match self {
            Self::Transport(reason) => reason.to_string(),
            Self::CallerIdentity(refusal) => refusal.to_string(),
            Self::HandlerRejectedPayload => HANDLER_REJECTED_PAYLOAD.to_string(),
        }
    }
}

/// The marker logged in place of an operation identifier that was never
/// read. Never an empty string, and never a guess.
pub(crate) const UNREAD_OPERATION: &str = "<unread>";

/// Refuses a connection: log it, write nothing, close cleanly.
///
/// Generic over the stream so the same code runs over a real
/// [`tokio::net::UnixStream`] and over an in-memory duplex a test can
/// read the far end of — which is how "zero response bytes, then a
/// clean close" is asserted rather than assumed.
pub(crate) async fn refuse<S>(stream: &mut S, connection: &ConnectionId, refusal: &Refusal<'_>)
where
    S: AsyncWrite + Unpin,
{
    let operation = refusal
        .operation
        .map_or(UNREAD_OPERATION, Operation::as_str);
    let received_name = refusal.received_name.map(escape_name_bytes);
    warn!(
        connection = connection.as_str(),
        reason = refusal.cause.label(),
        operation,
        received_name = received_name.as_deref().unwrap_or(UNREAD_OPERATION),
        "Registrar endpoint refused a connection: {}",
        refusal.cause.describe()
    );
    close(stream, connection).await;
}

/// Closes a stream cleanly, logging a shutdown failure as a diagnostic
/// rather than propagating it: the connection is over either way.
pub(crate) async fn close<S>(stream: &mut S, connection: &ConnectionId)
where
    S: AsyncWrite + Unpin,
{
    if let Err(err) = stream.shutdown().await {
        tracing::debug!(
            connection = connection.as_str(),
            "Registrar endpoint could not shut the connection down cleanly: {err}"
        );
    }
}
