version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      cargo-minor-patch:
        update-types:
          - "minor"
          - "patch"
      cargo-security:
        applies-to: "security-updates"
    labels:
      - "dependencies"
      - "rust"
      - "security"
    open-pull-requests-limit: 5
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-minor-patch:
        update-types:
          - "minor"
          - "patch"
      github-actions-security:
        applies-to: "security-updates"
    labels:
      - "dependencies"
      - "github-actions"
      - "security"
    open-pull-requests-limit: 5
  - package-ecosystem: "docker"
    directories:
      - "/docker/*"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
