//! The dedicated `bootroot-agent` config the internal profile renews
//! under, and the trust upserts a rotation applies to it.
//!
//! The internal profile runs in a **second** `bootroot-agent` host
//! process, supervised by the operator:
//!
//! ```text
//! bootroot-agent --config <secrets-directory>/registrar-internal/agent.toml
//! ```
//!
//! `init` writes the config and never starts it, exactly as it never
//! installs a supervisor for the service agents. Ordinary renewal begins
//! once the operator starts that process, which is why a `SIGHUP` that
//! matches no process is a successful outcome rather than proof of
//! renewal.
//!
//! The config is bootroot's alone. It is never a service agent config,
//! it carries no `ServiceEntry`, and its `[trust]` points at the private
//! [`crate::registrar::internal::CA_BUNDLE_FILE`] copy beside it rather
//! than the shared `secrets/certs/ca-bundle.pem` — so a rotation can
//! narrow this identity's trust without touching what a service reads.

use std::path::Path;

use anyhow::Result;

use crate::config::Settings;
use crate::registrar::REGISTRAR_INTERNAL_LABEL;
use crate::registrar::internal::{InternalCredentialError, InternalPaths};
use crate::secret::HmacSecret;
use crate::toml_util::{toml_encode_string, upsert_section_keys};

/// The instance label the internal identity is always composed at.
pub const INTERNAL_INSTANCE_ID: &str = "001";

/// The `agent.toml` section carrying the profile's trust settings.
const TRUST_SECTION: &str = "trust";

/// Everything the internal agent config is rendered from.
///
/// Every member is a value `init` already has in hand: there is no new
/// operator input and no new prompt.
#[derive(Debug, Clone)]
pub struct InternalAgentConfigParams<'a> {
    /// The deployment contact email, as the service agents use.
    pub email: &'a str,
    /// The step-ca ACME directory URL.
    pub server: &'a str,
    /// The deployment domain the SAN is composed under.
    pub domain: &'a str,
    /// The host label of the bootroot host.
    pub hostname: &'a str,
    /// The HTTP-01 responder URL.
    pub responder_url: &'a str,
    /// The HTTP-01 responder shared HMAC.
    pub responder_hmac: &'a HmacSecret,
    /// The EAB key identifier, when the deployment registered one.
    pub eab_kid: Option<&'a str>,
    /// The EAB HMAC, when the deployment registered one.
    pub eab_hmac: Option<&'a HmacSecret>,
    /// Fingerprints covering every certificate in the private bundle.
    pub trusted_ca_sha256: &'a [String],
}

/// Returns the `registration_id` the internal profile is keyed by.
///
/// Composed as `<host>-<component>`, the per-host multiplicity class's
/// shape, so it is unique on a deployment that runs more than one
/// bootroot host. It names no KV namespace — the internal config carries
/// no `[openbao]` section and polls nothing — but the field is required
/// and a placeholder that could collide would be worse than one that
/// cannot.
#[must_use]
pub fn internal_registration_id(hostname: &str) -> String {
    format!("{hostname}-{REGISTRAR_INTERNAL_LABEL}")
}

/// Renders the internal profile's complete `agent.toml`.
///
/// Rendered whole rather than upserted: this file has exactly one
/// author, so there is no operator customisation to preserve and no
/// reason for it to accumulate a second profile. A rotation edits only
/// the `[trust]` table, through [`build_internal_trust_updates`].
#[must_use]
pub fn render_internal_agent_config(
    paths: &InternalPaths,
    params: &InternalAgentConfigParams<'_>,
) -> String {
    let pins = render_pin_array(params.trusted_ca_sha256);
    let eab = match (params.eab_kid, params.eab_hmac) {
        (Some(kid), Some(hmac)) if !kid.is_empty() && !hmac.is_empty() => format!(
            "\n[eab]\nkid = {kid}\nhmac = {hmac}\n",
            kid = toml_encode_string(kid),
            hmac = toml_encode_string(hmac.expose()),
        ),
        _ => String::new(),
    };
    format!(
        "# Generated by `bootroot init`. This file is bootroot's own: it\n\
         # configures the second `bootroot-agent` process that renews the\n\
         # bootroot-internal registrar credential, and nothing else reads it.\n\
         #\n\
         #   bootroot-agent --config {config}\n\
         #\n\
         # The operator supervises that process; `bootroot init` does not\n\
         # start it and installs no supervisor for it.\n\
         email = {email}\n\
         server = {server}\n\
         domain = {domain}\n\
         \n\
         [acme]\n\
         directory_fetch_attempts = 10\n\
         directory_fetch_base_delay_secs = 1\n\
         directory_fetch_max_delay_secs = 10\n\
         poll_attempts = 15\n\
         poll_interval_secs = 2\n\
         http_responder_url = {responder_url}\n\
         http_responder_hmac = {responder_hmac}\n\
         http_responder_timeout_secs = 5\n\
         http_responder_token_ttl_secs = 300\n\
         account_key_path = {account_key}\n\
         \n\
         [retry]\n\
         backoff_secs = [5, 15, 60]\n\
         \n\
         [scheduler]\n\
         max_concurrent_issuances = 1\n\
         \n\
         [trust]\n\
         ca_bundle_path = {bundle}\n\
         trusted_ca_sha256 = {pins}\n\
         {eab}\n\
         [[profiles]]\n\
         registration_id = {registration_id}\n\
         service_name = {service_name}\n\
         instance_id = {instance}\n\
         hostname = {hostname}\n\
         \n\
         [profiles.paths]\n\
         cert = {cert}\n\
         key = {key}\n",
        config = paths.agent_config().display(),
        email = toml_encode_string(params.email),
        server = toml_encode_string(params.server),
        domain = toml_encode_string(params.domain),
        responder_url = toml_encode_string(params.responder_url),
        responder_hmac = toml_encode_string(params.responder_hmac.expose()),
        account_key = toml_encode_string(&paths.acme_account().display().to_string()),
        bundle = toml_encode_string(&paths.ca_bundle().display().to_string()),
        registration_id = toml_encode_string(&internal_registration_id(params.hostname)),
        service_name = toml_encode_string(REGISTRAR_INTERNAL_LABEL),
        instance = toml_encode_string(INTERNAL_INSTANCE_ID),
        hostname = toml_encode_string(params.hostname),
        cert = toml_encode_string(&paths.chain().display().to_string()),
        key = toml_encode_string(&paths.key().display().to_string()),
    )
}

/// Loads the dedicated config and holds it to every invariant the
/// generator gives it.
///
/// The config is a member of the all-or-none set, so "present" is not
/// the same question as "usable": a file that no longer parses, or that
/// has been pointed at another identity's key, describes a renewal
/// daemon that cannot start. Treating that as a provisioned credential
/// would let the privileged verbs run on a host where nothing renews
/// the certificate they authenticate with — which is precisely the
/// state the typed failure exists to name.
///
/// What is checked is what the generator fixes and a rotation is
/// allowed to change: the identity and the three file paths are
/// invariants, the pin list and the bundle path are rewritten by
/// Phases 3 and 6 and so are checked for shape rather than for value.
///
/// # Errors
///
/// Returns [`InternalCredentialError::Invalid`] when the file does not
/// parse, when it does not carry exactly the one internal profile, or
/// when any fixed path or the trust table has drifted.
pub fn load_internal_config(paths: &InternalPaths) -> Result<Settings, InternalCredentialError> {
    let path = paths.agent_config();
    let invalid = |reason: String| InternalCredentialError::Invalid {
        path: path.clone(),
        reason,
    };
    let settings = Settings::from_file(Some(path.clone()))
        .map_err(|err| invalid(format!("the generated config does not parse: {err}")))?;

    let [profile] = settings.profiles.as_slice() else {
        return Err(invalid(format!(
            "expected exactly one profile, found {}",
            settings.profiles.len()
        )));
    };
    if profile.service_name != REGISTRAR_INTERNAL_LABEL {
        return Err(invalid(format!(
            "the profile names service `{}` rather than `{REGISTRAR_INTERNAL_LABEL}`",
            profile.service_name
        )));
    }
    if profile.instance_id != INTERNAL_INSTANCE_ID {
        return Err(invalid(format!(
            "the profile names instance `{}` rather than `{INTERNAL_INSTANCE_ID}`",
            profile.instance_id
        )));
    }
    expect_path("profiles.paths.cert", &profile.paths.cert, &paths.chain()).map_err(&invalid)?;
    expect_path("profiles.paths.key", &profile.paths.key, &paths.key()).map_err(&invalid)?;
    let account_key = settings
        .acme
        .account_key_path
        .as_deref()
        .ok_or_else(|| invalid("acme.account_key_path is unset".to_string()))?;
    expect_path("acme.account_key_path", account_key, &paths.acme_account()).map_err(&invalid)?;
    let bundle = settings
        .trust
        .ca_bundle_path
        .as_deref()
        .ok_or_else(|| invalid("trust.ca_bundle_path is unset".to_string()))?;
    expect_path("trust.ca_bundle_path", bundle, &paths.ca_bundle()).map_err(&invalid)?;
    if settings.trust.trusted_ca_sha256.is_empty() {
        return Err(invalid("trust.trusted_ca_sha256 is empty".to_string()));
    }
    Ok(settings)
}

/// Reports a configured path that is not the fixed one the layout gives
/// it.
fn expect_path(field: &str, found: &Path, expected: &Path) -> Result<(), String> {
    if found == expected {
        return Ok(());
    }
    Err(format!(
        "{field} points at {} rather than {}",
        found.display(),
        expected.display()
    ))
}

/// Builds the `[trust]` pairs a rotation upserts into the internal
/// config.
///
/// Mirrors [`crate::trust_bootstrap::build_trust_updates`] so the
/// internal config and a service config cannot drift on the key
/// spellings, but points at the private bundle rather than a shared one.
#[must_use]
pub fn build_internal_trust_updates(
    paths: &InternalPaths,
    fingerprints: &[String],
) -> Vec<(&'static str, String)> {
    vec![
        ("ca_bundle_path", paths.ca_bundle().display().to_string()),
        ("trusted_ca_sha256", render_pin_array(fingerprints)),
    ]
}

/// Applies [`build_internal_trust_updates`] to an existing config.
///
/// # Errors
///
/// Returns an error when `contents` is not valid TOML.
pub fn upsert_internal_trust(
    contents: &str,
    paths: &InternalPaths,
    fingerprints: &[String],
) -> Result<String> {
    upsert_section_keys(
        contents,
        TRUST_SECTION,
        &build_internal_trust_updates(paths, fingerprints),
    )
}

/// Renders a fingerprint list as a TOML array literal.
fn render_pin_array(fingerprints: &[String]) -> String {
    format!(
        "[{}]",
        fingerprints
            .iter()
            .map(|value| toml_encode_string(value))
            .collect::<Vec<_>>()
            .join(", ")
    )
}

/// Returns the exact operator invocation that starts the internal
/// agent, for documentation and for the `init` summary.
#[must_use]
pub fn internal_agent_invocation(paths: &InternalPaths) -> String {
    format!("bootroot-agent --config {}", paths.agent_config().display())
}

/// The path a `pkill -HUP -f` pattern matches the internal agent by.
///
/// The pattern is the config path and nothing else: the internal agent
/// has no `ServiceEntry`, and the fixed path below the state-recorded
/// secrets directory is the only thing that distinguishes its command
/// line from every other `bootroot-agent` on the host.
#[must_use]
pub fn internal_signal_pattern(secrets_dir: &Path) -> String {
    InternalPaths::new(secrets_dir)
        .agent_config()
        .display()
        .to_string()
}
