#!/usr/bin/env python3
"""Validates and reads `deploy/runtime-images.json`.

The declaration records which exact upstream registry images this
revision of bootroot approves as runtime dependencies of its default
production stack. bootler reads it at an immutable bootroot revision
and binds its release recipes to it; this module is the bootroot side of
that contract: schema-1 format checks, and consistency of the declared
repository/tag with what the Compose sources actually run.

Subcommands:

- `check` validates the declaration and every supplied Compose set.
- `reference` checks one image reference found outside Compose (a CI
  pre-pull, say) against a declared role.
- `pins` validates the declaration and prints one tab-separated line
  per entry (`dependency repository tag digest lookup-tag`) for shell
  consumers such as the deploy no-build smoke.

Registry graph validation (index -> platform child -> config) is not
done here. It needs the network and belongs to bootler's release
resolver; this module is local and network-free apart from running
`docker compose config`, which only renders files.

Standard library only, and written to run on the oldest `python3` a
developer host is likely to carry: no `match`, no `X | Y` annotations.
"""

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile

LABEL = "validate-runtime-images"

SCHEMA_VERSION = 1
TOP_LEVEL_FIELDS = ("schema", "dependencies")
ENTRY_FIELDS = ("dependency", "repository", "tag", "version", "digest", "platforms")

DEFAULT_PLATFORM = "linux/amd64"

# The finite set of platform spellings a declaration may list. Linux
# only, explicit architecture, and the canonical OCI spelling of each
# (`linux/arm64/v8`, not `linux/arm64`). Listing a platform here is not
# a claim that bootroot supports it; the declaration's own `platforms`
# is that claim.
KNOWN_PLATFORMS = (
    "linux/amd64",
    "linux/arm64/v8",
    "linux/arm/v7",
    "linux/arm/v6",
    "linux/386",
    "linux/ppc64le",
    "linux/s390x",
    "linux/riscv64",
)

# Service classification for the selected production profile, bootler's
# default bootroot stack. Every service a rendered Compose model carries
# must appear in exactly one of these tables: an unlisted service is
# rejected rather than guessed at, so a caller-added runtime service
# cannot escape declaration coverage.
#
# Registry-backed services map to the declaration role whose image they
# run. The two OpenBao Agent sidecars are generated by `bootroot init`
# as a Compose override and run the OpenBao image.
REGISTRY_ROLE_SERVICES = {
    "openbao": "openbao",
    "openbao-agent-stepca": "openbao",
    "openbao-agent-responder": "openbao",
    "postgres": "postgres",
    "step-ca": "step-ca",
}

# Product-built services run an image bootroot builds itself, so it is
# not a registry dependency and must not be declared. The value is the
# unqualified repository the image must keep; this check does not
# rename it.
PRODUCT_BUILT_SERVICES = {
    "bootroot-http01": "bootroot-http01-responder",
}

# Optional monitoring services. They ship in both Compose files behind
# the `lan` / `public` profiles and are outside the selected production
# profile, so their images are deliberately absent from the declaration.
# They must stay profile-gated: one active by default would be an
# undeclared runtime image.
EXCLUDED_MONITORING_SERVICES = ("prometheus", "grafana", "grafana-public")

# Every profile name the Compose sources may use. A service gated on a
# profile outside this list is rejected: nobody has decided whether it
# ships.
KNOWN_PROFILES = ("lan", "public")

# Profile selections this validator can vouch for. Only the default
# (no profile) is the selected production profile; `lan` and `public`
# activate monitoring, which the declaration does not cover.
SUPPORTED_PROFILE_SELECTIONS = ()

# Variables whose value replaces a Compose image default. They are
# cleared from the render environment so a caller's installer seam
# cannot stand in for the source default under validation. Any other
# variable a supplied Compose file interpolates is cleared too.
IMAGE_OVERRIDE_VARIABLES = (
    "OPENBAO_IMAGE",
    "POSTGRES_IMAGE",
    "BOOTROOT_STEP_CA_IMAGE",
    "BOOTROOT_HTTP01_IMAGE",
    "PROMETHEUS_IMAGE",
    "GRAFANA_IMAGE",
)

# Dummy values for the variables the Compose files require with
# `${VAR:?...}`. They only let the render complete.
RENDER_ENV_FILE_CONTENTS = "POSTGRES_PASSWORD=validate-only\nGRAFANA_ADMIN_PASSWORD=validate-only\n"

DOCKER_HUB_DOMAIN = "docker.io"
DOCKER_HUB_LEGACY_DOMAIN = "index.docker.io"
DOCKER_HUB_OFFICIAL_NAMESPACE = "library"

DEPENDENCY_RE = re.compile(r"^[a-z0-9][a-z0-9_-]{0,62}$")
PLACEHOLDER_DEPENDENCIES = (
    "changeme",
    "dependency",
    "example",
    "none",
    "null",
    "placeholder",
    "tbd",
    "todo",
    "unknown",
    "xxx",
)
DIGEST_RE = re.compile(r"^sha256:[0-9a-f]{64}$")
TAG_RE = re.compile(r"^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$")
PATH_COMPONENT_RE = re.compile(r"^[a-z0-9]+(?:(?:[._]|__|-+)[a-z0-9]+)*$")
DOMAIN_RE = re.compile(
    r"^(?:[A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9-]*[A-Za-z0-9])"
    r"(?:\.(?:[A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9-]*[A-Za-z0-9]))*"
    r"(?::[0-9]+)?$"
)
# semver.org's reference expression, restricted to ASCII digits.
SEMVER_RE = re.compile(
    r"^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)"
    r"(?:-((?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)"
    r"(?:\.(?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?"
    r"(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$",
    re.ASCII,
)
INTERPOLATION_RE = re.compile(r"\$\{?([A-Za-z_][A-Za-z0-9_]*)")


class ValidationError(Exception):
    """A declaration or Compose source that does not satisfy the contract."""


class ToolError(Exception):
    """A failure to run the validation itself, as opposed to a finding."""


def reject_duplicate_keys(pairs):
    seen = {}
    for key, value in pairs:
        if key in seen:
            raise ValidationError(f"duplicate JSON key {key!r}")
        seen[key] = value
    return seen


def load_declaration(path):
    try:
        with open(path, encoding="utf-8") as handle:
            text = handle.read()
    except OSError as err:
        raise ToolError(f"reading declaration {path}: {err}") from err
    try:
        return json.loads(text, object_pairs_hook=reject_duplicate_keys)
    except json.JSONDecodeError as err:
        raise ValidationError(f"{path} is not valid JSON: {err}") from err


def is_integer(value):
    return isinstance(value, int) and not isinstance(value, bool)


def split_domain(name):
    """Splits a repository name into (explicit domain or None, remainder)."""
    first, sep, rest = name.partition("/")
    if sep and ("." in first or ":" in first or first == "localhost"):
        return first, rest
    return None, name


def normalize_repository(name):
    """Expands Docker Hub shorthand to a fully qualified repository.

    A one-segment name gains `docker.io/library/`, an unqualified
    multi-segment name gains `docker.io/`. A first segment that names a
    registry host (dotted, carrying a port, or `localhost`) is kept as
    that host and never read as a Docker Hub namespace.
    """
    domain, remainder = split_domain(name)
    if domain is None:
        domain = DOCKER_HUB_DOMAIN
    elif domain == DOCKER_HUB_LEGACY_DOMAIN:
        domain = DOCKER_HUB_DOMAIN
    if domain == DOCKER_HUB_DOMAIN and "/" not in remainder:
        remainder = f"{DOCKER_HUB_OFFICIAL_NAMESPACE}/{remainder}"
    return f"{domain}/{remainder}"


def familiar_name(repository):
    """Returns the short spelling Docker prints for a canonical repository."""
    library_prefix = f"{DOCKER_HUB_DOMAIN}/{DOCKER_HUB_OFFICIAL_NAMESPACE}/"
    if repository.startswith(library_prefix):
        return repository[len(library_prefix) :]
    hub_prefix = f"{DOCKER_HUB_DOMAIN}/"
    if repository.startswith(hub_prefix):
        return repository[len(hub_prefix) :]
    return repository


def repository_syntax_error(name):
    """Returns why `name` is not a valid repository, or None."""
    domain, remainder = split_domain(name)
    if domain is not None and not DOMAIN_RE.fullmatch(domain):
        return f"invalid registry host {domain!r}"
    components = remainder.split("/")
    for component in components:
        if not PATH_COMPONENT_RE.fullmatch(component):
            return f"invalid path component {component!r}"
    return None


def parse_image_reference(reference):
    """Splits `name[:tag][@digest]` into (name, tag or None, digest or None)."""
    name, _, digest = reference.partition("@")
    digest = digest or None
    tag = None
    last_slash = name.rfind("/")
    colon = name.rfind(":")
    if colon > last_slash:
        name, tag = name[:colon], name[colon + 1 :]
    error = repository_syntax_error(name)
    if error is not None:
        raise ValidationError(f"image reference {reference!r}: {error}")
    if tag is not None and not TAG_RE.fullmatch(tag):
        raise ValidationError(f"image reference {reference!r}: invalid tag {tag!r}")
    if digest is not None and not DIGEST_RE.fullmatch(digest):
        raise ValidationError(f"image reference {reference!r}: invalid digest {digest!r}")
    return name, tag, digest


def validate_entry(index, entry, selected_platform, errors):
    where = f"dependencies[{index}]"
    if not isinstance(entry, dict):
        errors.append(f"{where} must be an object")
        return None
    unknown = sorted(set(entry) - set(ENTRY_FIELDS))
    if unknown:
        errors.append(f"{where} has unknown fields: {', '.join(unknown)}")
    missing = [field for field in ENTRY_FIELDS if field not in entry]
    if missing:
        errors.append(f"{where} is missing fields: {', '.join(missing)}")

    dependency = entry.get("dependency")
    if "dependency" in entry:
        if not isinstance(dependency, str) or not DEPENDENCY_RE.fullmatch(dependency):
            errors.append(
                f"{where}.dependency {dependency!r} must be a lowercase ASCII identifier "
                "starting with an alphanumeric and containing only alphanumerics, '-' or '_'"
            )
            dependency = None
        elif dependency in PLACEHOLDER_DEPENDENCIES:
            errors.append(f"{where}.dependency {dependency!r} is a placeholder")
            dependency = None
    label = f"{where} ({dependency})" if dependency else where

    repository = entry.get("repository")
    if "repository" in entry:
        if not isinstance(repository, str):
            errors.append(f"{label}.repository must be a string")
        else:
            error = repository_syntax_error(repository)
            domain, _ = split_domain(repository)
            if error is not None:
                errors.append(f"{label}.repository {repository!r}: {error}")
            elif domain is None:
                errors.append(
                    f"{label}.repository {repository!r} must name its registry explicitly, "
                    f"e.g. {normalize_repository(repository)!r}"
                )
            elif normalize_repository(repository) != repository:
                errors.append(
                    f"{label}.repository {repository!r} is not canonical; "
                    f"use {normalize_repository(repository)!r}"
                )

    tag = entry.get("tag")
    if "tag" in entry and (not isinstance(tag, str) or not TAG_RE.fullmatch(tag)):
        errors.append(f"{label}.tag {tag!r} is not a valid image tag")

    # The comparison version is reviewed independently of the tag: no
    # version is inferred from the upstream label, and none is checked
    # against it.
    if "version" in entry:
        version = entry["version"]
        if version is not None and (
            not isinstance(version, str) or not SEMVER_RE.fullmatch(version)
        ):
            errors.append(f"{label}.version {version!r} must be a canonical SemVer string or null")

    if "digest" in entry:
        digest = entry["digest"]
        if not isinstance(digest, str) or not DIGEST_RE.fullmatch(digest):
            errors.append(
                f"{label}.digest {digest!r} must be 'sha256:' followed by 64 lowercase hex digits"
            )
        elif len(set(digest[len("sha256:") :])) == 1:
            errors.append(f"{label}.digest {digest!r} is a placeholder")

    if "platforms" in entry:
        platforms = entry["platforms"]
        if not isinstance(platforms, list) or not platforms:
            errors.append(f"{label}.platforms must be a nonempty list")
        else:
            seen = set()
            for platform in platforms:
                if not isinstance(platform, str) or platform not in KNOWN_PLATFORMS:
                    errors.append(f"{label}.platforms has unsupported platform {platform!r}")
                elif platform in seen:
                    errors.append(f"{label}.platforms lists {platform!r} more than once")
                else:
                    seen.add(platform)
            if selected_platform not in platforms:
                errors.append(
                    f"{label}.platforms does not include the selected platform "
                    f"{selected_platform!r}"
                )
    return dependency


def validate_declaration(document, selected_platform):
    """Returns the entries keyed by role, or raises with every finding."""
    if selected_platform not in KNOWN_PLATFORMS:
        raise ValidationError(f"unsupported selected platform {selected_platform!r}")
    errors = []
    if not isinstance(document, dict):
        raise ValidationError("declaration must be a JSON object")
    unknown = sorted(set(document) - set(TOP_LEVEL_FIELDS))
    if unknown:
        errors.append(f"unknown top-level fields: {', '.join(unknown)}")
    if "schema" not in document:
        errors.append("missing top-level field: schema")
    elif not is_integer(document["schema"]) or document["schema"] != SCHEMA_VERSION:
        errors.append(f"unsupported schema {document['schema']!r}; expected {SCHEMA_VERSION}")
    entries = document.get("dependencies")
    if "dependencies" not in document:
        errors.append("missing top-level field: dependencies")
        entries = []
    elif not isinstance(entries, list):
        errors.append("dependencies must be a list")
        entries = []

    by_role = {}
    for index, entry in enumerate(entries):
        role = validate_entry(index, entry, selected_platform, errors)
        if role is None:
            continue
        if role in by_role:
            errors.append(f"dependency {role!r} is declared more than once")
            continue
        by_role[role] = entry
    if errors:
        raise ValidationError("\n".join(errors))
    return by_role


def compose_variables(paths):
    names = set()
    for path in paths:
        try:
            with open(path, encoding="utf-8") as handle:
                names.update(INTERPOLATION_RE.findall(handle.read()))
        except OSError as err:
            raise ToolError(f"reading compose file {path}: {err}") from err
    return names


def render_environment(paths):
    """Returns the caller's environment minus everything that could change the render.

    Compose selects files through `COMPOSE_FILE`, profiles through
    `COMPOSE_PROFILES`, and so on, so every `COMPOSE_*` variable goes.
    So does every variable a supplied file interpolates, which covers
    the image overrides and any other variable a fixture introduces.
    """
    cleared = set(IMAGE_OVERRIDE_VARIABLES) | compose_variables(paths)
    return {
        key: value
        for key, value in os.environ.items()
        if key not in cleared and not key.startswith("COMPOSE_")
    }


def render_compose_model(paths, docker):
    """Renders the full model of one Compose set, every profile included.

    `--profile '*'` renders profile-gated services too, so a service
    gated on an unknown profile is visible instead of silently absent.
    This is render-only inspection: nothing is started.
    """
    with tempfile.TemporaryDirectory() as tmp:
        env_file = os.path.join(tmp, "render.env")
        with open(env_file, "w", encoding="utf-8") as handle:
            handle.write(RENDER_ENV_FILE_CONTENTS)
        command = [docker, "compose", "--env-file", env_file, "--profile", "*"]
        for path in paths:
            command.extend(["-f", path])
        command.extend(["config", "--format", "json"])
        try:
            result = subprocess.run(
                command,
                env=render_environment(paths),
                capture_output=True,
                text=True,
                check=False,
            )
        except OSError as err:
            raise ToolError(f"running {docker} compose config: {err}") from err
    if result.returncode != 0:
        raise ToolError(
            f"docker compose config failed for {' + '.join(paths)}:\n{result.stderr.strip()}"
        )
    try:
        model = json.loads(result.stdout)
    except json.JSONDecodeError as err:
        raise ToolError(f"docker compose config printed invalid JSON: {err}") from err
    services = model.get("services")
    if not isinstance(services, dict):
        raise ToolError("docker compose config printed no services mapping")
    return services


def check_image_against_entry(service, image, entry):
    name, tag, digest = parse_image_reference(image)
    repository = normalize_repository(name)
    problems = []
    if repository != entry["repository"]:
        problems.append(
            f"repository {repository!r} does not match declared {entry['repository']!r}"
        )
    if tag is None:
        problems.append(f"carries no tag; declared tag is {entry['tag']!r}")
    elif tag != entry["tag"]:
        problems.append(f"tag {tag!r} does not match declared {entry['tag']!r}")
    if digest is not None and digest != entry["digest"]:
        problems.append(f"digest {digest} does not match declared {entry['digest']}")
    return [f"service {service!r} image {image!r}: {problem}" for problem in problems]


def validate_profile_selection(selected_profiles):
    """Rejects any profile selection other than the selected production profile.

    The selection is a validation input rather than a declaration field:
    schema 1 has no profile concept, so a declaration can only vouch for
    the default active set.
    """
    errors = []
    for profile in selected_profiles:
        if profile not in KNOWN_PROFILES:
            errors.append(f"unknown profile selection {profile!r}")
        elif profile not in SUPPORTED_PROFILE_SELECTIONS:
            errors.append(
                f"unsupported profile selection {profile!r}: it activates services outside "
                "the selected production profile, which the declaration does not cover"
            )
    if errors:
        raise ValidationError("\n".join(errors))


def validate_compose_set(label, services, declared):
    """Checks one rendered model against the declaration, returning findings."""
    errors = []
    active_roles = {}
    for service in sorted(services):
        definition = services[service] or {}
        profiles = definition.get("profiles") or []
        unknown_profiles = [profile for profile in profiles if profile not in KNOWN_PROFILES]
        if unknown_profiles:
            errors.append(
                f"service {service!r} uses unknown profiles: {', '.join(unknown_profiles)}"
            )
        active = not profiles
        image = definition.get("image")

        if service in EXCLUDED_MONITORING_SERVICES:
            if active:
                errors.append(
                    f"excluded monitoring service {service!r} is active by default; "
                    "monitoring is outside the selected production profile"
                )
            continue
        if service in PRODUCT_BUILT_SERVICES:
            expected = PRODUCT_BUILT_SERVICES[service]
            if not isinstance(image, str):
                errors.append(f"product-built service {service!r} has no image")
                continue
            try:
                name, _, _ = parse_image_reference(image)
            except ValidationError as err:
                errors.append(str(err))
                continue
            if name != expected:
                errors.append(
                    f"product-built service {service!r} image {image!r} must keep the "
                    f"repository {expected!r}"
                )
            continue
        if service not in REGISTRY_ROLE_SERVICES:
            errors.append(
                f"unclassified service {service!r} (image {image!r}); every service must be "
                "classified as a declared registry role, a product-built image, or an "
                "excluded monitoring service"
            )
            continue

        role = REGISTRY_ROLE_SERVICES[service]
        if not active:
            # A registry-role service moved behind a profile no longer runs
            # by default; the missing-role check below reports its role.
            continue
        entry = declared.get(role)
        if entry is None:
            errors.append(f"service {service!r} runs role {role!r}, which is not declared")
            continue
        if not isinstance(image, str):
            errors.append(f"service {service!r} has no image")
            continue
        try:
            errors.extend(check_image_against_entry(service, image, entry))
        except ValidationError as err:
            errors.append(str(err))
        active_roles.setdefault(role, []).append(service)

    for role in sorted(set(declared) - set(active_roles)):
        errors.append(
            f"declared dependency {role!r} is not run by any default active service "
            "(extra declaration)"
        )
    return [f"{label}: {error}" for error in errors]


def command_check(args):
    validate_profile_selection(args.profile or [])
    declared = validate_declaration(load_declaration(args.declaration), args.platform)
    print(f"[{LABEL}] OK: {args.declaration} is a valid schema-{SCHEMA_VERSION} declaration")
    errors = []
    for compose_set in args.compose_set or []:
        label = " + ".join(compose_set)
        services = render_compose_model(compose_set, args.docker)
        found = validate_compose_set(label, services, declared)
        if found:
            errors.extend(found)
        else:
            print(f"[{LABEL}] OK: {label} default services match the declaration")
    if errors:
        raise ValidationError("\n".join(errors))


def command_pins(args):
    declared = validate_declaration(load_declaration(args.declaration), args.platform)
    for role in sorted(declared):
        entry = declared[role]
        lookup = f"{familiar_name(entry['repository'])}:{entry['tag']}"
        print("\t".join((role, entry["repository"], entry["tag"], entry["digest"], lookup)))


def command_reference(args):
    declared = validate_declaration(load_declaration(args.declaration), args.platform)
    entry = declared.get(args.role)
    if entry is None:
        raise ValidationError(f"{args.source}: role {args.role!r} is not declared")
    errors = check_image_against_entry(args.source, args.image, entry)
    if errors:
        raise ValidationError("\n".join(errors))
    print(f"[{LABEL}] OK: {args.source} uses {args.image!r}, the declared {args.role!r} image")


def build_parser():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--declaration", required=True, help="path to runtime-images.json")
    parser.add_argument(
        "--platform",
        default=DEFAULT_PLATFORM,
        help=f"selected release platform (default {DEFAULT_PLATFORM})",
    )
    commands = parser.add_subparsers(dest="command", required=True)

    check = commands.add_parser("check", help="validate the declaration and Compose sources")
    check.add_argument(
        "--compose-set",
        action="append",
        nargs="+",
        metavar="FILE",
        help="one Compose model: a base file followed by any overrides; repeatable",
    )
    check.add_argument(
        "--profile",
        action="append",
        help="a Compose profile the validated deployment selects; repeatable",
    )
    check.add_argument("--docker", default="docker", help="docker executable")
    check.set_defaults(handler=command_check)

    pins = commands.add_parser("pins", help="print the declared pins as TSV")
    pins.set_defaults(handler=command_pins)

    reference = commands.add_parser(
        "reference", help="check one image reference found outside Compose against a role"
    )
    reference.add_argument("--source", required=True, help="where the reference was found")
    reference.add_argument("role", help="declared dependency role")
    reference.add_argument("image", help="image reference to check")
    reference.set_defaults(handler=command_reference)
    return parser


def main(argv):
    args = build_parser().parse_args(argv)
    try:
        args.handler(args)
    except ValidationError as err:
        for line in str(err).splitlines():
            print(f"[{LABEL}] FAIL: {line}", file=sys.stderr)
        return 1
    except ToolError as err:
        print(f"[{LABEL}] ERROR: {err}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
